## IMPORTAR LIBRERIAS

In [1]:

import pandas as pd
import numpy as np
import pickle
import os

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

## 1: Carga del conjunto de datos
Análisis de sentimientos:

Los modelos Naive Bayes son muy útiles cuando queremos analizar sentimientos, clasificar textos en tópicos o recomendaciones, ya que las características de estos desafíos cumplen muy bien con los supuestos teóricos y metodológicos del modelo.

En este proyecto practicarás con un conjunto de datos para crear un clasificador de reseñas de la tienda de Google Play.

In [19]:
url = "https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv"
df = pd.read_csv(url)
df.head()

,package_name,review,polarity
0,com.facebook.katana,privacy at least put some option appear offli...,0
1,com.facebook.katana,"messenger issues ever since the last update, ...",0
2,com.facebook.katana,profile any time my wife or anybody has more ...,0
3,com.facebook.katana,the new features suck for those of us who don...,0
4,com.facebook.katana,forced reload on uploading pic on replying co...,0


In [4]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   package_name  891 non-null    object
 1   review        891 non-null    object
 2   polarity      891 non-null    int64 
dtypes: int64(1), object(2)
memory usage: 21.0+ KB


package_name    0
review          0
polarity        0
dtype: int64

## 2: Estudio de variables y su contenido

En este caso, tenemos solo 3 variables: 2 predictoras y una etiqueta dicotómica. De las dos predictoras, realmente solo nos interesa la parte del comentario, ya que el hecho de clasificar un comentario en positivo o negativo dependerá de su contenido, no de la aplicación de la que se haya escrito. Por lo tanto, la variable package_name habría que eliminarla.

### Eliminar espacios y convertir a minúsculas el texto:

In [14]:
df['review'] = df['review'].str.strip().str.lower()

print(df.columns.tolist())


['review', 'polarity']


### Dividir el conjunto de datos en train y test: X_train, X_test, y_train, y_test


In [20]:
X = df["review"]
y = df["polarity"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train.head()

485     best app i can't believe that it is free! the...
622     good good for slow connection this uc minilit...
854     #1 great game. challenging to the point where...
536     very reliable syncing but......the web ui loo...
728     didn't work couldn't use it with my note 4, i...
Name: review, dtype: object

### Transformar el texto en una matriz de recuento de palabras. 
Esta es una forma de obtener características numéricas a partir del texto. Para ello, utilizamos el conjunto de train para entrenar el transformador y la aplicamos en test:

In [42]:
vec_model = CountVectorizer(stop_words="english")

X_train_vec = vec_model.fit_transform(X_train).toarray()
X_test_vec = vec_model.transform(X_test).toarray()


print(f"\nNúmero de palabras únicas encontradas: {len(vec_model.get_feature_names_out())}")
print(f"Forma de X_train: {X_train_vec.shape}")


Número de palabras únicas encontradas: 3272
Forma de X_train: (712, 3272)


## 3: Construye un naive bayes
Comienza a resolver el problema implementando un modelo del que tendrás que elegir cuál de las tres implementaciones utilizar: GaussianNB, MultinomialNB o BernoulliNB, según lo que hemos estudiado en el módulo. Prueba ahora a entrenarlo con las dos otras implementaciones y confirma si el modelo que has elegido es el adecuado.

In [36]:
resultados = {}
# MULTINOMIAL NAIVE BAYES

model = MultinomialNB()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)
y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0])

In [43]:
acc_mltd = accuracy_score(y_test, y_pred)
resultados['Multinomial'] = acc_mltd
print("Accuracy:", accuracy_score(y_test, y_pred))
print(f"Precisión: {acc_mltd:.4f} ({acc_mltd*100:.2f}%)")
print(classification_report(y_test, y_pred))

Accuracy: 0.8547486033519553
Precisión: 0.8547 (85.47%)
              precision    recall  f1-score   support

           0       0.84      0.96      0.90       117
           1       0.89      0.66      0.76        62

    accuracy                           0.85       179
   macro avg       0.87      0.81      0.83       179
weighted avg       0.86      0.85      0.85       179



In [48]:
# BERNOULLI NAIVE BAYES

bnb = BernoulliNB()
bnb.fit(X_train_vec, y_train)
y_pred_bnb = bnb.predict(X_test_vec)
y_pred_bnb


array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0])

In [51]:
acc_bnb = accuracy_score(y_test, y_pred_bnb)
resultados['Bernoulli'] = acc_bnb
print("Accuracy:", accuracy_score(y_test, y_pred_bnb))
print(f"Precisión: {acc_bnb:.4f} ({acc_bnb*100:.2f}%)")
print(classification_report(y_test, y_pred_bnb))

Accuracy: 0.7821229050279329
Precisión: 0.7821 (78.21%)
              precision    recall  f1-score   support

           0       0.76      0.97      0.85       117
           1       0.87      0.44      0.58        62

    accuracy                           0.78       179
   macro avg       0.82      0.70      0.72       179
weighted avg       0.80      0.78      0.76       179



In [52]:
# GAUSSIAN NAIVE BAYES
gnb = GaussianNB()

gnb.fit(X_train_vec, y_train)
y_pred_gnb = gnb.predict(X_test_vec)
y_pred_gnb


array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0])

In [56]:
acc_gnb = accuracy_score(y_test, y_pred_gnb)
resultados['Gaussian'] = acc_gnb
print("Accuracy:", accuracy_score(y_test, y_pred_gnb))
print(f"Precisión: {acc_gnb:.4f} ({acc_gnb*100:.2f}%)")
print(classification_report(y_test, y_pred_gnb))


Accuracy: 0.8156424581005587
Precisión: 0.8156 (81.56%)
              precision    recall  f1-score   support

           0       0.84      0.89      0.86       117
           1       0.76      0.68      0.72        62

    accuracy                           0.82       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.81      0.82      0.81       179



In [57]:
print("COMPARACIÓN DE MODELOS")
print("="*50)
for modelo, precision in resultados.items():
    print(f"{modelo}: {precision:.4f} ({precision*100:.2f}%)")

mejor_modelo = max(resultados, key=resultados.get)
print(f"\n🏆 Mejor modelo: {mejor_modelo}")

COMPARACIÓN DE MODELOS
Multinomial: 0.8547 (85.47%)
Bernoulli: 0.7821 (78.21%)
Gaussian: 0.8156 (81.56%)

🏆 Mejor modelo: Multinomial


## 4: Optimiza el modelo anterior
Después de entrenar el modelo en sus tres implementaciones, elige la mejor opción y trata de optimizar sus resultados con un random forest, si es posible.



In [61]:
tfidf = TfidfVectorizer(stop_words="english")

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_tfidf, y_train)

y_pred_lr = lr.predict(X_test_tfidf)

print(f"precicion: {accuracy_score(y_test, y_pred_lr):.4f}({accuracy_score(y_test, y_pred_lr)*100:.2f}%)")

precicion: 0.7821(78.21%)


## 5: Guarda el modelo
Almacena el modelo en la carpeta correspondiente.



In [63]:
os.makedirs("models", exist_ok=True)

with open("models/naive_bayes_model.pkl", "wb") as f:
    pickle.dump(model, f)